version: '3.3'

services:
  flask_server:
    build:
      context: .
      dockerfile: ./image_class_server/docker/Dockerfile
    # '/start' is the shell script used to run the service
    command: /start_server
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app

  steamlit_ui:
    build:
      context: .
      dockerfile: ./image_class_client/docker/Dockerfile
    command: /start_client
    volumes:
      - .:/app
    ports:
      - 8501:8501
    depends_on:
      - flask_server

